# This is a basic workflow to help you get started with Actions

name: Echo on Repository Dispatch

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [dependency-updated]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run: 'echo "dependency-updated event recieved"'

      - name: Echo the payload
        run: 'echo "Recieved Payload: ${{ github.event.client_payload }}"'
