name: Upgrade Dependencies on Repository Dispatch

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [dependency-updated]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  upgrade-deps:
    name: Upgrade Dependencies
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - uses: ./upgrade-dependencies-and-automerge
        id: upgrade-deps
        with:
          github-access-token: ${{ secrets.REPO_ACCESS_PAT }}
          reason: "${{ github.event.client_payload.dependency }} updated"

      - name: Auto Approve Pull Request
        if: steps.upgrade-deps.outputs.pull-request-number != ''
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.REPO_ACCESS_PAT }}
          pull-request-number: ${{ steps.upgrade-deps.outputs.pull-request-number }}

